package Strings;

/*
This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘.

Note: You may assume that at most one additional character can be added to t.
 */

import java.util.HashMap;

public class SpotTheDifference {
    public char findTheDifference(String s, String t)
    {
        HashMap<Character, Integer> hmap = new HashMap<Character, Integer>();
        for(char c: s.toCharArray())
        {
            hmap.put(c, hmap.getOrDefault(c,0)+ 1);
        }
        for(char c: t.toCharArray())
        {
            if(!hmap.containsKey(c) || hmap.get(c) == 0)
                return c;
            else
                hmap.put(c, hmap.get(c)-1);
        }
        return ' ';
    }
}
